[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_2026_05_19 = "EXV3KYGvRm3Xir1gf94hF7LsupEC5scJUUDCpQ3eXnFu"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
